services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: npg_H67IacJmbDxV
      POSTGRES_DB: yt-serverless
      POSTGRES_USER: neondb_owner

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mynestjs:
    build: ./
    ports:
      - 3000:3000
    command: npm run start:dev # Hot reload command
    depends_on:
      - db
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    #   - NODE_ENV=development
    working_dir: /myapp
    # volumes:
    #   - ./src:/myapp/src
